[project]
name = "bedrock-webmap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-ge>=0.3.2",
    "geopandas>=1.1.1",
    "marimo>=0.14.17",
]
